# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-19 20:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, null=True)),
                ('prenom', models.CharField(max_length=50, null=True)),
                ('pseudo', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('numero', models.IntegerField()),
                ('photo', models.FileField(blank=True, null=True, upload_to='./repertoire_app/Photos contacts/')),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('pseudo', models.CharField(max_length=60)),
                ('password', models.CharField(default=False, max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.IntegerField()),
                ('statut', models.CharField(default='Aucun statut', max_length=150)),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='./repertoire_app/Photos de profils/')),
                ('user', models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
