# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-23 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repertoire_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='static/images/Photos contacts/'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, upload_to='static/images/Photos de profils/'),
        ),
    ]
